### ISSUE TITLE
Wrong Replace Bundle Short Version

### ISSUE THREAD

**Issue by MeGaPk** [BOOMik/steps-set-ios-version#4]
<img width="534" alt="screen shot 2017-03-06 at 09 49 28" src="https://cloud.githubusercontent.com/assets/892182/23601074/4d884be2-0252-11e7-982e-3195a1fb0da2.png">
<img width="666" alt="screen shot 2017-03-06 at 09 49 46" src="https://cloud.githubusercontent.com/assets/892182/23601075/4d88d706-0252-11e7-9891-8b9a8ff07a70.png">

**Comment by Dave005** [comment]
I fixed this issue in my fork : https://github.com/Dave005/steps-set-ios-version.git and made a pull request, you can use this fork instead until it gets merged

**Comment by KirillAshikhmin** [comment]
Fixed in 2.0,0
